### ISSUE TITLE
Hosting links

### ISSUE THREAD

**Issue by zhuraavl** [mbusson/_SassyPug#2]
Hi, your work is outstanding, thank you for it! But when I try to download my project to the hosting and click on the link, for example site.com/section/two — it says there's an error and url doesn't exist. The same thing happens when I try to update any other page than the home. By the way, it works and you can go to any page. Everything works on the local hosting. I can't imagine what is the problem.

**Comment by baptistebriel** [comment]
Are you saying you have issues deploying to a production server ?
Did you maybe forgot the `.htaccess` ? Do you have the same issue using [`biggie`](https://github.com/baptistebriel/biggie) ?

**Comment by zhuraavl** [comment]
indeed, forgotten.
Added this

```
# Do not remove this line or mod_rewrite rules and search engine friendly URLs will stop working
RewriteBase /
RewriteEngine on
```

But does not work

`biggie`  too

I do this on a subdomain. This can be important?

**Comment by baptistebriel** [comment]
Your .htaccess file needs to be like [this](https://github.com/baptistebriel/biggie/blob/master/.htaccess):

```
RewriteEngine On
RewriteBase /

RewriteRule ^index\.html$ - [L] 
RewriteCond %{REQUEST_FILENAME} !-f 
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . /index.html [L]
```

It should work on a sub domain as well; that's how I do it!

**Comment by zhuraavl** [comment]
Thank you! Working!
